/**
 * robots.txt — generated by Next at build time.
 *
 * Disallow auth / admin / pay surfaces from search indexing. The
 * authenticated dashboard, admin console, and payment landing pages
 * have no SEO value.
 *
 * `APP_URL` wins over `NEXT_PUBLIC_APP_URL` (runtime > build-inlined),
 * matching the precedence used in oauth callbacks and the sitemap.
 */
import type { MetadataRoute } from 'next';

function baseUrl(): string {
    const u = process.env.APP_URL || process.env.NEXT_PUBLIC_APP_URL || 'https://silkroadai.io';
    return u.replace(/\/$/, '');
}

export default function robots(): MetadataRoute.Robots {
    const base = baseUrl();
    return {
        rules: [
            {
                userAgent: '*',
                allow: ['/', '/pricing', '/models', '/docs', '/gpu', '/terms', '/privacy', '/refund'],
                disallow: [
                    '/admin',
                    '/admin/',
                    '/api/',
                    '/dashboard',
                    '/keys',
                    '/balance',
                    '/usage',
                    '/pay',
                    '/portal/',
                ],
            },
        ],
        sitemap: `${base}/sitemap.xml`,
    };
}
