/**
 * sitemap.xml — generated by Next at build time from this file.
 *
 * Lists the public, indexable routes. Authenticated routes
 * (`/dashboard`, `/keys`, etc.) and admin pages are intentionally
 * omitted — they're behind cookie auth and have no value in search
 * results.
 *
 * If `APP_URL` is set, it wins over `NEXT_PUBLIC_APP_URL` (matches the
 * OAuth-base-URL precedence used elsewhere — runtime > build-inlined).
 */
import type { MetadataRoute } from 'next';

function baseUrl(): string {
    const u = process.env.APP_URL || process.env.NEXT_PUBLIC_APP_URL || 'https://silkroadai.io';
    return u.replace(/\/$/, '');
}

export default function sitemap(): MetadataRoute.Sitemap {
    const base = baseUrl();
    const lastModified = new Date();
    return [
        {
            url: `${base}/`,
            lastModified,
            changeFrequency: 'weekly',
            priority: 1.0,
        },
        {
            url: `${base}/pricing`,
            lastModified,
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: `${base}/models`,
            lastModified,
            changeFrequency: 'daily',
            priority: 0.8,
        },
        {
            // W7 D4 PR-G: public integration docs — agent-by-agent
            // quickstart for Cursor / Cline / Continue / Claude Code
            // Desktop / Python SDK / Node SDK.
            url: `${base}/docs`,
            lastModified,
            changeFrequency: 'weekly',
            priority: 0.8,
        },
        {
            // W7 PR-P: GPU rental landing — H100 / H200 / B300.
            // Public page targeting "GPU 租赁" / "AI 算力" SEO.
            url: `${base}/gpu`,
            lastModified,
            changeFrequency: 'weekly',
            priority: 0.7,
        },
        {
            // W7 D4: real signup page (no longer a 404 placeholder — see
            // PR #28 F2-quick which routed the landing CTA to /login as a
            // band-aid until this page existed).
            url: `${base}/portal/register`,
            lastModified,
            changeFrequency: 'monthly',
            priority: 0.7,
        },
        {
            url: `${base}/login`,
            lastModified,
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: `${base}/terms`,
            lastModified,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/privacy`,
            lastModified,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/refund`,
            lastModified,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
    ];
}
