/**
 * sitemap.xml — generated by Next at build time from this file.
 *
 * Lists the public, indexable routes. Authenticated routes
 * (`/dashboard`, `/keys`, etc.) and admin pages are intentionally
 * omitted — they're behind cookie auth and have no value in search
 * results.
 *
 * If `APP_URL` is set, it wins over `NEXT_PUBLIC_APP_URL` (matches the
 * OAuth-base-URL precedence used elsewhere — runtime > build-inlined).
 */
import type { MetadataRoute } from 'next';

function baseUrl(): string {
    const u =
        process.env.APP_URL ||
        process.env.NEXT_PUBLIC_APP_URL ||
        'https://silkroadai.io';
    return u.replace(/\/$/, '');
}

export default function sitemap(): MetadataRoute.Sitemap {
    const base = baseUrl();
    const lastModified = new Date();
    return [
        {
            url: `${base}/`,
            lastModified,
            changeFrequency: 'weekly',
            priority: 1.0,
        },
        {
            url: `${base}/pricing`,
            lastModified,
            changeFrequency: 'weekly',
            priority: 0.9,
        },
        {
            url: `${base}/models`,
            lastModified,
            changeFrequency: 'daily',
            priority: 0.8,
        },
        // /portal/register intentionally absent — the portal has no email-
        // only signup UI yet (the public CTA "立即开始 →" routes to /login,
        // which exposes Google + GitHub OAuth as the de-facto signup path).
        // Once W7 D4 ships a proper /portal/register page, re-add it with
        // priority 0.7 between /models and /login.
        {
            url: `${base}/login`,
            lastModified,
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: `${base}/terms`,
            lastModified,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/privacy`,
            lastModified,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
        {
            url: `${base}/refund`,
            lastModified,
            changeFrequency: 'yearly',
            priority: 0.3,
        },
    ];
}
